# Should players be given the pylon guide book when they first join?
pylon-guide-on-first-join: true

# The default interval (in Minecraft ticks) between each block tick
# Most blocks have a custom tick interval which can be changed in their settings
default-tick-interval: 20

# The number of errors a block can throw before it is disabled
allowed-block-errors: 5

# The number of errors a entity can throw before it is disabled
allowed-entity-errors: 5

# The interval (in Minecraft ticks), between WAILA checks
waila-tick-interval: 1

# The interval (in Minecraft ticks) between fluid network ticks
fluid-tick-interval: 5

block-data-autosave-interval-seconds: 60

entity-data-autosave-interval-seconds: 60

research:
  enabled: true
  # The interval (in Minecraft ticks) between when Pylon checks for unresearched items in inventories
  tick-interval: 20
  # Formula
  # calculated = base-amount * researchCost * multiplier
  # spawnedConfetti = max(calculated, max-amount)
  confetti:
    base-amount: 70.0
    multiplier: 0.2
    max-amount: 700 # must be an integer

pipe-placement:
  # The interval (in Minecraft ticks) between pipe placement task ticks
  tick-interval: 1

  # Recommended to keep this low to make pipe placement easier
  # Might break pipe placement if set very high due to chunkloading mechanics
  max-distance: 5

# How many characters a line can be before it is split into a new line when translating
translation-wrap-limit: 64

# The interval (in Minecraft ticks) between metrics data being saved
metrics-save-interval-ticks: 6000

# Explosion default drop chance, expressed as a decimal percentage
# 1.0 always drops, 0.0 never drops
default-explosion-drop-chance: 0.5

# Keys of the items you want to disable. You can get an item's key with /pylon key
#
# Disabling an item will remove it from the guide, stop players from being able to craft it,
# and prevent players from using it in any way. Any disabled items that already exist ingame
# will become functional again when the item is removed from the disabled-items list.
#
# Be aware that disabling an item that's used as an ingredient for other items will mean that
# those items can't be crafted.
disabled-items: []
