name: Create GitHub Release

on:
  push:
    tags: ['*']

jobs:
  build:
    uses: ./.github/workflows/gradle.yml
    with:
      version: ${{ github.ref_name }}
      
  github-release:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Download Rebar
      uses: actions/download-artifact@v4.1.8
      with:
        name: rebar-${{ github.ref_name }}

    - name: Create Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.ACCESS_TOKEN }}
        draft: false
        prerelease: false
        automatic_release_tag: ${{ github.ref_name }}
        title: Release ${{ github.ref_name }}
        files: rebar-*.jar